### ISSUE TITLE
ids[0] must not be null

### ISSUE THREAD

**Issue by huynn0105** [kee-org/flutter_autofill_service#5]
![image](https://github.com/kee-org/flutter_autofill_service/assets/51359128/9d6de7c1-eef8-4f5c-ae31-358cbcf8c06b)

**Comment by luckyrat** [comment]
How can it be reproduced?

What version of Android were you using?

What version of Kee Vault?

What app, browser and/or website triggered the message to appear?

**Comment by huynn0105** [comment]
bug on production app. 
android version 13
flutter_autofill_service: ^0.14.0
any browser and/or website.

**Comment by luckyrat** [comment]
I still can't reproduce this. Please try with 0.19.0 and open a new issue with reproduction steps if you still see the problem. Thanks.
