### ISSUE TITLE
A problem occurred configuring project ':flutter_autofill_service'.

### ISSUE THREAD

**Issue by KetanSatani-TheOneTech** [kee-org/flutter_autofill_service#7]
I have added the service in android manifest file. and my flutter and dart versions are stated below. I am using latest package version.

Flutter: 3.16.0
Dart: 3.2.0

Error
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_autofill_service'.
> Failed to notify project evaluation listener.
   > 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation.getTarget()'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 718ms
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by luckyrat** [comment]
Such useless error messages are often a result of mismatched Java versions. First thing to try is using the latest master from this repo rather than the older package on pub.dev.

**Comment by KetanSatani-TheOneTech** [comment]
Okay I will try and get back here.

**Comment by KetanSatani-TheOneTech** [comment]
@luckyrat 
I tried latest master from this repo. But now facing this issue.

![Screenshot 2023-12-07 at 5 44 43 PM](https://github.com/kee-org/flutter_autofill_service/assets/153186382/fbc4b673-52b6-4c29-a815-8fc0a7383f38)

**Comment by luckyrat** [comment]
The build requirements are now updated (Kotlin 1.9) so please try the latest master and open a new issue if there are still any unresolved build problems for us to look into. Thanks.
